#For product service 
spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


